---
- name: Update Packages
  hosts: all_servers
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      tags:
        - update

    - name: Upgrade packages
      apt:
        upgrade: yes
      tags:
        - update
